INSERT INTO dictionary (Word, Meaning, Example)
VALUES
('abate', 'to become weaker; to decrease in strength', 'The storm abated after several hours.'),
('benevolent', 'kind and generous', 'She was known for her benevolent nature and charitable work.'),
('catalyst', 'a substance that speeds up a chemical reaction without being consumed itself', 'The enzyme acted as a catalyst in the reaction.'),
('diligent', 'hard-working and conscientious', 'She was a diligent student who always completed her assignments on time.'),
('ephemeral', 'lasting for a very short time', 'The beauty of the cherry blossoms is ephemeral.'),
('facetious', 'treating serious issues with deliberately inappropriate humor', 'His facetious remarks lightened the mood in the room.'),
('gregarious', 'sociable and outgoing', 'He was known for his gregarious personality and love of parties.'),
('hedonist', 'someone who seeks pleasure as the highest good', 'He lived his life as a hedonist, always seeking out new experiences.'),
('impetuous', 'acting or done quickly and without thought or care', 'Her impetuous decision led to unforeseen consequences.'),
('jubilant', 'feeling or expressing great happiness and triumph', 'The team was jubilant after winning the championship.'),
('knell', 'the sound of a bell, especially when rung solemnly for a death or funeral', 'The knell of the church bells echoed through the village.'),
('lament', 'to express sorrow or regret for; to mourn', 'She lamented the loss of her beloved pet.'),
('mendacious', 'not telling the truth; lying', 'His mendacious behavior eventually caught up with him.'),
('nefarious', 'wicked, villainous, or criminal', 'The nefarious plot was uncovered by the authorities.'),
('obfuscate', 'to deliberately make something unclear or confusing', 'The politician tried to obfuscate the issue with vague statements.'),
('parsimonious', 'unwilling to spend money or use resources; stingy', 'He was known for his parsimonious habits, never wasting a penny.'),
('querulous', 'habitually complaining or whining', 'The querulous customer demanded to speak to the manager.'),
('recalcitrant', 'stubbornly resistant to authority or control', 'The recalcitrant student refused to follow the teacher\'s instructions.'),
('sagacious', 'having or showing keen mental discernment and good judgment; wise or shrewd', 'His sagacious advice helped guide me through difficult times.'),
('taciturn', 'reserved or uncommunicative in speech; saying little', 'He was known for his taciturn nature, rarely speaking unless spoken to.'),
('ubiquitous', 'present, appearing, or found everywhere', 'In today\'s society, smartphones are ubiquitous.'),
('venerate', 'to regard with great respect; to revere', 'The ancient Egyptians venerated cats as sacred animals.'),
('wanton', 'deliberate and unprovoked; unrestrained', 'The wanton destruction of the environment angered conservationists.'),
('xenophobic', 'having or showing a dislike of or prejudice against people from other countries', 'His xenophobic attitudes were evident in his anti-immigrant rhetoric.'),
('yoke', 'a wooden crosspiece that is fastened over the necks of two animals and attached to the plow or cart that they are to pull', 'The farmer placed the yoke on the oxen before plowing the field.'),
('zealot', 'a person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals', 'The religious zealot preached his beliefs on the street corner.'),
('alacrity', 'brisk and cheerful readiness', 'She accepted the challenge with alacrity and enthusiasm.'),
('belligerent', 'hostile and aggressive', 'The belligerent drunk started a fight at the bar.'),
('complacent', 'showing smug or uncritical satisfaction with oneself or one\'s achievements', 'His complacent attitude prevented him from reaching his full potential.'),
('demeanor', 'outward behavior or bearing', 'Despite his rough appearance, his demeanor was gentle and kind.'),
('enigmatic', 'difficult to interpret or understand; mysterious', 'The enigmatic smile on her face left me wondering what she was thinking.'),
('frugal', 'sparing or economical with regard to money or food', 'She lived a frugal lifestyle, saving money wherever she could.'),
('gregarious', 'fond of company; sociable', 'His gregarious personality made him the life of the party.'),
('harrowing', 'acutely distressing', 'The harrowing tales of survival touched the hearts of everyone who heard them.'),
('indolent', 'wanting to avoid activity or exertion; lazy', 'His indolent attitude meant that he rarely completed his assignments on time.'),
('juxtapose', 'to place or deal with close together for contrasting effect', 'The director juxtaposed scenes of luxury with those of poverty to highlight the disparities in society.'),
('kinetic', 'relating to or resulting from motion', 'The kinetic energy of the moving car was converted into heat upon impact.'),
('languid', 'displaying or having a disinclination for physical exertion or effort; slow and relaxed', 'She lay in bed in a languid state, not wanting to get up.'),
('malleable', 'easily influenced; pliable', 'His opinions were malleable and often changed depending on who he was talking to.'),
('nonchalant', 'feeling or appearing casually calm and relaxed; not displaying anxiety, interest, or enthusiasm', 'He acted nonchalant about the news, but I could tell he was worried.'),
('obsequious', 'obedient or attentive to an excessive or servile degree', 'The obsequious waiter hovered around our table, eager to please.'),
('pervasive', 'spreading widely throughout an area or a group of people', 'The pervasive smell of smoke lingered in the air long after the fire had been extinguished.'),
('quixotic', 'exceedingly idealistic; unrealistic and impractical', 'His quixotic quest for world peace seemed noble but unrealistic.'),
('resplendent', 'attractive and impressive through being richly colorful or sumptuous', 'The bride looked resplendent in her wedding gown.'),
('serendipity', 'the occurrence and development of events by chance in a happy or beneficial way', 'Their meeting was pure serendipity, leading to a lifelong friendship.'),
('ambivalent', 'having mixed feelings or contradictory ideas about something or someone', 'She felt ambivalent about accepting the job offer.'),
('bucolic', 'relating to the pleasant aspects of the countryside and country life', 'They enjoyed a bucolic weekend in the countryside, away from the hustle and bustle of the city.'),
('capricious', 'given to sudden and unaccountable changes of mood or behavior', 'Her capricious nature made it difficult to predict how she would react.'),
('deleterious', 'causing harm or damage', 'The deleterious effects of smoking on health are well documented.'),
('effervescent', 'bubbly, lively, and enthusiastic', 'Her effervescent personality brightened up the room.'),
('fervent', 'having or displaying a passionate intensity', 'He was a fervent supporter of human rights.'),
('gregarious', 'fond of company; sociable', 'Her gregarious nature made her popular among her peers.'),
('haphazard', 'lacking any obvious principle of organization', 'The books on the shelf were arranged in a haphazard manner.'),
('impetuous', 'acting or done quickly and without thought or care', 'Her impetuous decision led to unintended consequences.'),
('juxtaposition', 'the fact of two things being seen or placed close together with contrasting effect', 'The juxtaposition of wealth and poverty in the city was striking.'),
('kaleidoscope', 'a constantly changing pattern or sequence of elements', 'The city was a kaleidoscope of colors and sounds.'),
('labyrinth', 'a complicated irregular network of passages or paths in which it is difficult to find one\'s way; a maze', 'The old castle was like a labyrinth, with secret passages and hidden chambers.'),
('mellifluous', 'sweet or musical; pleasant to hear', 'Her mellifluous voice captivated the audience.'),
('nebulous', 'in the form of a cloud or haze; hazy', 'The details of the plan were still nebulous and unclear.'),
('obfuscate', 'to deliberately make something unclear or confusing', 'The politician obfuscated the issue with technical jargon.'),
('perfunctory', 'carried out with minimal effort or reflection', 'His greeting was perfunctory, lacking any genuine warmth.'),
('quintessential', 'representing the most perfect or typical example of a quality or class', 'The city skyline is often seen as the quintessential image of urban life.'),
('recalcitrant', 'having an obstinately uncooperative attitude towards authority or discipline', 'The recalcitrant student refused to follow the rules.'),
('salubrious', 'health-giving; healthy', 'The mountain air was salubrious and invigorating.'),
('trepidation', 'a feeling of fear or agitation about something that may happen', 'She entered the haunted house with trepidation, unsure of what to expect.'),
('ubiquitous', 'present, appearing, or found everywhere', 'In today\'s society, social media is ubiquitous.'),
('vexatious', 'causing or tending to cause annoyance, frustration, or worry', 'The vexatious problem took hours to solve.'),
('whimsical', 'playfully quaint or fanciful, especially in an appealing and amusing way', 'The whimsical decorations gave the room a magical atmosphere.'),
('xenial', 'of, relating to, or constituting hospitality or relations between host and guest', 'Their xenial attitude made us feel welcome in their home.'),
('yearn', 'have an intense feeling of longing for something, typically something that one has lost or been separated from', 'She yearned for the warmth of her childhood home.'),
('zenith', 'the highest point reached by a celestial or other object; the peak', 'His career reached its zenith when he won the Nobel Prize.'),
('acumen', 'the ability to make good judgments and quick decisions, typically in a particular domain', 'His business acumen helped him build a successful company.'),
('bolster', 'support or strengthen; prop up', 'The new evidence bolstered her case.'),
('cogent', 'clear, logical, and convincing', 'He presented a cogent argument that persuaded everyone in the room.'),
('dearth', 'a scarcity or lack of something', 'There was a dearth of fresh water in the desert.'),
('eloquent', 'fluent or persuasive in speaking or writing', 'Her eloquent speech moved the audience to tears.'),
('fractious', 'irritable and quarrelsome', 'The fractious children argued over who would get the last piece of cake.'),
('garrulous', 'excessively talkative, especially on trivial matters', 'The garrulous old man talked for hours about his travels.'),
('histrionic', 'overly theatrical or melodramatic in character or style', 'Her histrionic behavior was exhausting to deal with.'),
('indomitable', 'impossible to subdue or defeat', 'Despite facing numerous obstacles, she possessed an indomitable spirit.'),
('jubilant', 'feeling or expressing great happiness and triumph', 'The team was jubilant after winning the championship.'),
('kowtow', 'act in an excessively subservient manner', 'He refused to kowtow to his boss\'s unreasonable demands.'),
('lucid', 'clearly expressed and easy to understand', 'Her instructions were lucid and easy to follow.'),
('magnanimous', 'very generous or forgiving, especially toward a rival or someone less powerful than oneself', 'She showed a magnanimous gesture by forgiving her enemy.'),
('nadir', 'the lowest point in the fortunes of a person or organization', 'His career hit a nadir when he was fired from his job.'),
('opulent', 'ostentatiously rich and luxurious or lavish', 'The opulent mansion was filled with expensive furnishings and artwork.'),
('pervasive', 'spreading widely throughout an area or a group of people', 'The pervasive influence of social media is evident in everyday life.'),
('querulous', 'complaining in a petulant or whining manner', 'The querulous customer demanded to speak to the manager.'),
('resilient', 'able to withstand or recover quickly from difficult conditions', 'The resilient community bounced back after the natural disaster.'),
('sanguine', 'optimistic or positive, especially in an apparently bad or difficult situation', 'Despite facing setbacks, she remained sanguine about the future.'),
('tenuous', 'very weak or slight', 'The tenuous connection between the two events was difficult to prove.'),
('ubiquitous', 'present, appearing, or found everywhere', 'Smartphones have become ubiquitous in modern society.'),
('vociferous', 'expressing or characterized by vehement opinions; loud and forceful', 'The vociferous protesters demanded action from the government.'),
('wistful', 'having or showing a feeling of vague or regretful longing', 'She gazed out the window with a wistful expression, reminiscing about the past.'),
('zealous', 'having or showing zeal; fervent', 'He was a zealous supporter of environmental causes, volunteering his time and resources to help protect the planet.'),
('aplomb', 'self-confidence or assurance, especially when in a demanding situation', 'She handled the difficult situation with aplomb.'),
('benevolent', 'well-meaning and kindly', 'The benevolent old man donated generously to charity.'),
('candor', 'the quality of being open and honest in expression; frankness', 'She appreciated his candor and honesty.'),
('disparate', 'essentially different in kind; not allowing comparison', 'The two cultures had disparate traditions and customs.'),
('efficacious', 'successful in producing a desired or intended result; effective', 'The medicine proved to be efficacious in treating the illness.'),
('fathom', 'understand (a difficult problem or an enigmatic person) after much thought', 'He couldn\'t fathom why she had left him.'),
('garrulous', 'excessively talkative, especially on trivial matters', 'The garrulous old lady talked nonstop about her grandchildren.'),
('harrow', 'cause distress to', 'The news of the accident harrowed the entire community.'),
('indefatigable', 'persisting tirelessly', 'His indefatigable spirit kept him going despite the challenges he faced.'),
('jovial', 'cheerful and friendly', 'His jovial demeanor always lifted the mood of those around him.'),
('kinetic', 'relating to or resulting from motion', 'The kinetic energy of the moving car was immense.'),
('luminous', 'full of or shedding light; bright or shining, especially in the dark', 'The moon cast a luminous glow over the landscape.'),
('mendacious', 'not telling the truth; lying', 'His mendacious statements eventually caught up with him.'),
('nefarious', 'wicked or criminal', 'The nefarious activities of the gang were finally brought to light.'),
('obfuscate', 'render obscure, unclear, or unintelligible', 'The politician tried to obfuscate the facts to avoid scrutiny.'),
('pernicious', 'having a harmful effect, especially in a gradual or subtle way', 'The pernicious influence of gossip can destroy reputations.'),
('quintessential', 'representing the most perfect or typical example of a quality or class', 'The film is considered the quintessential romantic comedy.'),
('recalcitrant', 'having an obstinately uncooperative attitude towards authority or discipline', 'The recalcitrant student refused to comply with the teacher\'s instructions.'),
('salient', 'most noticeable or important', 'The salient feature of the landscape was the towering mountain peak.'),
('taciturn', 'reserved or uncommunicative in speech; saying little', 'He was a taciturn man who preferred to listen rather than speak.'),
('ubiquitous', 'present, appearing, or found everywhere', 'In today\'s world, smartphones are ubiquitous.'),
('veracity', 'conformity to facts; accuracy', 'The veracity of his statements was called into question.'),
('wanton', 'deliberate and unprovoked', 'The wanton destruction of property angered the community.'),
('xenophobic', 'having or showing a dislike of or prejudice against people from other countries', 'His xenophobic remarks sparked controversy and outrage.'),
('yoke', 'a wooden crosspiece that is fastened over the necks of two animals and attached to the plow or cart that they are to pull', 'The oxen wore a heavy yoke as they pulled the plow through the field.'),
('zealot', 'a person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals', 'The zealot preached his beliefs to anyone who would listen.'),
('altruistic', 'showing a disinterested and selfless concern for the well-being of others; unselfish', 'Her altruistic actions helped countless people in need.'),
('belligerent', 'hostile and aggressive', 'The belligerent country threatened to declare war on its neighbors.'),
('complacent', 'showing smug or uncritical satisfaction with oneself or one\'s achievements', 'His complacent attitude hindered his personal growth.'),
('dichotomy', 'a division or contrast between two things that are or are represented as being opposed or entirely different', 'The film explores the dichotomy between good and evil.'),
('eloquent', 'fluent or persuasive in speaking or writing', 'His eloquent speech moved the audience to tears.'),
('frugal', 'sparing or economical with regard to money or food', 'She lived a frugal lifestyle, saving money wherever she could.'),
('gregarious', 'fond of company; sociable', 'Her gregarious personality made her popular among her peers.'),
('harrowing', 'acutely distressing', 'The harrowing tales of survival touched the hearts of everyone who heard them.'),
('indolent', 'wanting to avoid activity or exertion; lazy', 'His indolent attitude meant that he rarely completed his assignments on time.'),
('juxtapose', 'to place or deal with close together for contrasting effect', 'The director juxtaposed scenes of luxury with those of poverty to highlight the disparities in society.'),
('kinetic', 'relating to or resulting from motion', 'The kinetic energy of the moving car was converted into heat upon impact.'),
('languid', 'displaying or having a disinclination for physical exertion or effort; slow and relaxed', 'She lay in bed in a languid state, not wanting to get up.'),
('malleable', 'easily influenced; pliable', 'His opinions were malleable and often changed depending on who he was talking to.'),
('nonchalant', 'feeling or appearing casually calm and relaxed; not displaying anxiety, interest, or enthusiasm', 'He acted nonchalant about the news, but I could tell he was worried.'),
('obsequious', 'obedient or attentive to an excessive or servile degree', 'The obsequious waiter hovered nearby, eager to fulfill their every request.'),
('pugnacious', 'eager or quick to argue, quarrel, or fight', 'The pugnacious boxer never backed down from a challenge.'),
('quixotic', 'exceedingly idealistic; unrealistic and impractical', 'His quixotic quest for perfection often led to disappointment.'),
('resplendent', 'attractive and impressive through being richly colorful or sumptuous', 'The bride looked resplendent in her wedding gown.'),
('sardonic', 'grimly mocking or cynical', 'His sardonic sense of humor often left others feeling uneasy.'),
('taciturn', 'reserved or uncommunicative in speech; saying little', 'The taciturn man rarely spoke unless spoken to first.'),
('ubiquitous', 'present, appearing, or found everywhere', 'In modern society, smartphones are ubiquitous.'),
('vehement', 'showing strong feeling; forceful, passionate, or intense', 'She made a vehement argument in favor of stricter regulations.'),
('winsome', 'attractive or appealing in appearance or character', 'Her winsome smile charmed everyone she met.'),
('xenial', 'relating to hospitality or relations between host and guest', 'Their xenial welcome made us feel at home in their country.'),
('yoke', 'a wooden crosspiece that is fastened over the necks of two animals and attached to the plow or cart that they are to pull', 'The oxen strained against the heavy yoke as they plowed the field.'),
('zealot', 'a person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals', 'The zealot devoted his life to his cause, never wavering in his beliefs.'),
('abate', 'to become less intense or widespread', 'The storm began to abate as the winds died down.'),
('beleaguer', 'to lay siege to; beset with difficulties', 'The company was beleaguered by financial troubles.'),
('cogitate', 'to think deeply about something', 'He sat silently, cogitating on the problem at hand.'),
('demeanor', 'outward behavior or bearing', 'Her calm demeanor helped her handle stressful situations.'),
('egregious', 'outstandingly bad; shocking', 'The company made an egregious error in their accounting.'),
('fledgling', 'a person or organization that is immature, inexperienced, or underdeveloped', 'The fledgling company struggled to compete with established competitors.'),
('glib', 'fluent and voluble but insincere and shallow', 'He gave a glib response without fully considering the question.'),
('heinous', 'utterly odious or wicked', 'The crime he committed was truly heinous.'),
('impetuous', 'acting or done quickly and without thought or care', 'His impetuous decision had serious consequences.'),
('jocular', 'fond of or characterized by joking; humorous or playful', 'His jocular demeanor made him popular with his colleagues.'),
('knell', 'the sound of a bell, especially when rung solemnly for a death or funeral', 'The knell of the church bell echoed through the village.'),
('lament', 'a passionate expression of grief or sorrow', 'She wrote a lament for her lost love.'),
('magnate', 'a wealthy and influential person, especially in business', 'He was a magnate in the tech industry, with vast resources at his disposal.'),
('nadir', 'the lowest point in the fortunes of a person or organization', 'The company hit rock bottom, reaching its nadir during the economic downturn.'),
('obstreperous', 'noisy and difficult to control', 'The obstreperous children disrupted the classroom with their constant chatter.'),
('pensive', 'engaged in, involving, or reflecting deep or serious thought', 'She sat by the window, lost in pensive contemplation.'),
('quixotic', 'exceedingly idealistic; unrealistic and impractical', 'His quixotic quest for perfection often led to disappointment.'),
('relegate', 'consign or dismiss to an inferior rank or position', 'He felt relegated to the sidelines while others took center stage.'),
('serendipity', 'the occurrence and development of events by chance in a happy or beneficial way', 'Their meeting was pure serendipity, leading to a lifelong friendship.'),
('taciturn', 'reserved or uncommunicative in speech; saying little', 'The taciturn man rarely spoke unless spoken to first.'),
('ubiquitous', 'present, appearing, or found everywhere', 'In modern society, smartphones are ubiquitous.'),
('vociferous', 'expressing or characterized by vehement opinions; loud and forceful', 'The vociferous protesters demanded action from the government.'),
('wistful', 'having or showing a feeling of vague or regretful longing', 'She gazed out the window with a wistful expression, reminiscing about the past.'),
('xenial', 'relating to hospitality or relations between host and guest', 'Their xenial welcome made us feel at home in their country.'),
('yield', 'to produce or provide (a natural, agricultural, or industrial product)', 'The farm yielded a bountiful harvest of fruits and vegetables.'),
('zenith', 'the highest point reached by a celestial or other object; the peak', 'His career reached its zenith when he won the Nobel Prize.'),
('affable', 'friendly, good-natured, or easy to talk to', 'He had an affable personality that made everyone feel welcome.'),
('banal', 'so lacking in originality as to be obvious and boring', 'His speech was banal, filled with clichés and platitudes.'),
('candid', 'truthful and straightforward; frank', 'She appreciated his candid remarks, even if they were sometimes blunt.'),
('vex', 'to make (someone) feel annoyed, frustrated, or worried, especially with trivial matters', 'Her constant complaints vexed him to no end.'),
('wily', 'skilled at gaining an advantage, especially deceitfully', 'The wily old fox always managed to outsmart the other animals in the forest.'),
('xenophobic', 'having or showing a dislike of or prejudice against people from other countries', 'His xenophobic attitudes made him unwelcome in many social circles.'),
('yearn', 'to have an intense feeling of longing for something, typically something that one has lost or been separated from', 'She yearned for the freedom of her youth, before responsibilities weighed her down.'),
('zealot', 'a person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals', 'The zealot preached his beliefs to anyone who would listen.');



